<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[899,1,49] published at 2011-09-01 00:06:14 from #187 by 2602-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>新浪微博-随时随地分享身边的新鲜事儿</title>
<meta name="Keywords" content="新浪微博,新浪围脖,名人微博,名人围脖,微博,围脖,新浪,围观" /> 
<meta name="Description" content="新浪微博是全中国最主流，最具人气，当前最火爆的微博产品。用一句话随意记录生活，用手机随时随地发微博。迅速获取最热最火最快最酷最新的资讯。手机微博weibo.cn，发送任意短信到 1066888866开通微博。" /> 

<meta http-equiv=X-UA-Compatible content=IE=EmulateIE7 />
<meta name="msapplication-tooltip" content="新浪微博" />
<meta name="msapplication-window" content="width=1024;height=768" />
<meta name="msapplication-task" content="name=新浪微博; action-uri=/; icon-uri=http://img1.t.sinajs.cn/t35/style/images/common/favicon/home.ico" />
<meta name="msapplication-task" content="name=我的微博; action-uri=/; icon-uri=http://img1.t.sinajs.cn/t35/style/images/common/favicon/mypage.ico" />
<meta name="msapplication-task" content="name=微博广场; action-uri=/pub/?source=toptray; icon-uri=http://img1.t.sinajs.cn/t35/style/images/common/favicon/square.ico" />
<meta content="#2994ce" name="msapplication-navbutton-color" />
<meta name="msapplication-starturl" content="./" /> 

<script type="text/javascript">
var $CONFIG = {
	$lang			: "zh",
	$oid			: "",
	$uid			: "",
	$severtime		: "1318641150",
	$token			: "b85b158144832b8f50aaa02074b1e391",
	$str_uid		: "da7b68b67a251021a3f973cb34da481c",
	$product		: "miniblog",
	$pageid			: "yunying_unlogin3",
	$cuser_status	: "full",
	$skin			: "skin_001",
	$domain         : "weibo.com/",
	$FW			    : "0"
	
};
var scope = $CONFIG;
scope.version = "20111014174826";
</script><link href="http://img.t.sinajs.cn/t35/style/css/tlogin/tlogin_1.css?version=20111014174826" type="text/css" rel="stylesheet" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<script type="text/javascript" src="http://js.t.sinajs.cn/t35/miniblog/js/lang_zh.js?version=20111014174826"></script>

<script type="text/javascript">
    scope.redirect = "";  
</script>
<link rel="apple-touch-icon-precomposed" href="http://img.t.sinajs.cn/t35/style/images/common/ipad/ipad_logo.png" /> 
</head>
<body>
<div class="MB_wrap">
  <div class="login_top"> <a href="" class="llink"></a>
    <div class="logoLink"></div>
  </div>
  <div class="login_body">
    <div class="login_l">

<div class="tit"><script>document.write("<scri"+"pt  type='text/javascript' src = 'http://ta.sass.sina.com.cn/front/deliver?psId=PDPS000000025446&d="+new Date().getTime()+"'></scri"+"pt>");</script></div>

      <div class="talking"> <strong class="">正在热议：</strong>
        <div class="coverl"></div>
        <div class="coverr"></div>
        <div class="acticle" id="topicBoxCon">
		<ul class="acticle_list" id="acticle_list">
	    <li><a target="_blank" href="http://weibo.com/zt/s?k=10401&hasori=1" target="_blank">连上7天的周末</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10442&hasori=1" target="_blank">九月CPI涨6.1%</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10412&hasori=1" target="_blank">地球太危险了</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10078&hasori=1" target="_blank">《倾世皇妃》</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10424&hasori=1" target="_blank">硬币VS纸币</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10441&hasori=1" target="_blank">广州暴雨</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10421&hasori=1" target="_blank">苹果推出iOS 5系统</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10449" target="_blank">内蒙农民微博卖土豆</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10363&hasori=1" target="_blank">2012考研开始报名</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10327&hasori=1" target="_blank">你要考公务员吗</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10414&hasori=1" target="_blank">好姑娘的标准</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10401&hasori=1" target="_blank">连上7天的周末</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10442&hasori=1" target="_blank">九月CPI涨6.1%</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10412&hasori=1" target="_blank">地球太危险了</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10078&hasori=1" target="_blank">《倾世皇妃》</a></li>
		    <li><a target="_blank" href="http://weibo.com/zt/s?k=10424&hasori=1" target="_blank">硬币VS纸币</a></li>
	</ul>
        </div>
      </div>
      <div class="talking_list">
      	<div class="tList_mdu1">
        <dl class="manlist">
          <dt>这些人正在用微博</dt>
          <dd>
            <ul class="userlist">
<li><a onclick='GB_SUDA._S_uaTrack("tblog_other_using","head_pic:1778742953");window.open(this.href);return false' href="http://weibo.com/1778742953" target="_blank"><img uid= imgtype="head" pop="ture" src="http://tp2.sinaimg.cn/1778742953/50/5609683559/0" title="张靓颖"/></a>
<a onclick='GB_SUDA._S_uaTrack("tblog_other_using","pet_name:1778742953");window.open(this.href);return false' href="http://weibo.com/1778742953" title="张靓颖" target="_blank">张靓颖</a>

</li>
<li><a onclick='GB_SUDA._S_uaTrack("tblog_other_using","head_pic:1354645954");window.open(this.href);return false' href="http://weibo.com/1354645954" target="_blank"><img uid= imgtype="head" pop="ture" src="http://tp3.sinaimg.cn/1354645954/50/5608901509/0" title="徐冬梅咖啡妞"/></a>
<a onclick='GB_SUDA._S_uaTrack("tblog_other_using","pet_name:1354645954");window.open(this.href);return false' href="http://weibo.com/1354645954" title="徐冬梅咖啡妞" target="_blank">徐冬梅咖啡妞</a>

</li>
<li><a onclick='GB_SUDA._S_uaTrack("tblog_other_using","head_pic:1494848464");window.open(this.href);return false' href="http://weibo.com/1494848464" target="_blank"><img uid= imgtype="head" pop="ture" src="http://tp1.sinaimg.cn/1494848464/50/5612708571/1" title="宁财神"/></a>
<a onclick='GB_SUDA._S_uaTrack("tblog_other_using","pet_name:1494848464");window.open(this.href);return false' href="http://weibo.com/1494848464" title="宁财神" target="_blank">宁财神</a>

</li>
<li><a onclick='GB_SUDA._S_uaTrack("tblog_other_using","head_pic:1687429295");window.open(this.href);return false' href="http://weibo.com/1687429295" target="_blank"><img uid= imgtype="head" pop="ture" src="http://tp4.sinaimg.cn/1687429295/50/5607140529/0" title="何韵诗HOCC"/></a>
<a onclick='GB_SUDA._S_uaTrack("tblog_other_using","pet_name:1687429295");window.open(this.href);return false' href="http://weibo.com/1687429295" title="何韵诗HOCC" target="_blank">何韵诗HOCC</a>

</li>
<li><a onclick='GB_SUDA._S_uaTrack("tblog_other_using","head_pic:1265596061");window.open(this.href);return false' href="http://weibo.com/1265596061" target="_blank"><img uid= imgtype="head" pop="ture" src="http://tp2.sinaimg.cn/1265596061/50/5602656452/1" title="峦树微博"/></a>
<a onclick='GB_SUDA._S_uaTrack("tblog_other_using","pet_name:1265596061");window.open(this.href);return false' href="http://weibo.com/1265596061" title="峦树微博" target="_blank">峦树微博</a>

</li>
<li><a onclick='GB_SUDA._S_uaTrack("tblog_other_using","head_pic:1659631214");window.open(this.href);return false' href="http://weibo.com/1659631214" target="_blank"><img uid= imgtype="head" pop="ture" src="http://tp3.sinaimg.cn/1659631214/50/1279884707/1" title="张俊以"/></a>
<a onclick='GB_SUDA._S_uaTrack("tblog_other_using","pet_name:1659631214");window.open(this.href);return false' href="http://weibo.com/1659631214" title="张俊以" target="_blank">张俊以</a>

</li>
<li><a onclick='GB_SUDA._S_uaTrack("tblog_other_using","head_pic:1752502537");window.open(this.href);return false' href="http://weibo.com/1752502537" target="_blank"><img uid= imgtype="head" pop="ture" src="http://tp2.sinaimg.cn/1752502537/50/5607570510/1" title="潘瑋柏"/></a>
<a onclick='GB_SUDA._S_uaTrack("tblog_other_using","pet_name:1752502537");window.open(this.href);return false' href="http://weibo.com/1752502537" title="潘瑋柏" target="_blank">潘瑋柏</a>

</li>
<li><a onclick='GB_SUDA._S_uaTrack("tblog_other_using","head_pic:1303977362");window.open(this.href);return false' href="http://weibo.com/1303977362" target="_blank"><img uid= imgtype="head" pop="ture" src="http://tp3.sinaimg.cn/1303977362/50/5611154779/0" title="容祖儿"/></a>
<a onclick='GB_SUDA._S_uaTrack("tblog_other_using","pet_name:1303977362");window.open(this.href);return false' href="http://weibo.com/1303977362" title="容祖儿" target="_blank">容祖儿</a>

</li>
<li><a onclick='GB_SUDA._S_uaTrack("tblog_other_using","head_pic:1574525494");window.open(this.href);return false' href="http://weibo.com/1574525494" target="_blank"><img uid= imgtype="head" pop="ture" src="http://tp3.sinaimg.cn/1574525494/50/5612650691/1" title="王喆同学"/></a>
<a onclick='GB_SUDA._S_uaTrack("tblog_other_using","pet_name:1574525494");window.open(this.href);return false' href="http://weibo.com/1574525494" title="王喆同学" target="_blank">王喆同学</a>

</li>
<img src="http://rs.sinajs.cn/mini.gif?t=w1&uids=1778742953,1354645954,1494848464,1687429295,1265596061,1659631214,1752502537,1303977362,1574525494" style="width:0px;height:0px;" alt="" /> 
</ul>
          </dd>
        </dl>
        <dl class="manlist">
          <dt>有趣的人</dt>
          <dd>
             <ul class="userlist">
<li><a href="http://weibo.com/kikilqp" target="_blank"><img src="http://tp2.sinaimg.cn/1294007181/50/5613098014/0" imgtype="head" uid="1294007181" title="大鸟kiki" pop="true" /></a><a href="http://weibo.com/1294007181" title="刘琪鹏" target="_blank">刘琪鹏</a></li>
<li><a href="http://weibo.com/shuyihe79" target="_blank"><img src="http://tp3.sinaimg.cn/1417226830/50/5609039606/0" imgtype="head" uid="1417226830" title="兔小铱铱" pop="true" /></a><a href="http://weibo.com/1417226830" title="Sss铱铱ssS" target="_blank">Sss铱铱ssS</a></li>
<li><a href="http://weibo.com/lovemioo" target="_blank"><img src="http://tp1.sinaimg.cn/1604532144/50/1291439745/0" imgtype="head" uid="1604532144" title="小怪物不吃肉" pop="true" /></a><a href="http://weibo.com/1604532144" title="小怪物不吃肉" target="_blank">小怪物不吃肉</a></li>
<li><a href="http://weibo.com/lovewiffy" target="_blank"><img src="http://tp1.sinaimg.cn/1745377732/50/5608265037/0" imgtype="head" uid="1745377732" title="pinkywiffy菲呀菲" pop="true" /></a><a href="http://weibo.com/1745377732" title="pinky_wiffy" target="_blank">pinky_wiffy</a></li>
<li><a href="http://weibo.com/1734775494" target="_blank"><img src="http://tp3.sinaimg.cn/1734775494/50/5610116470/0" imgtype="head" uid="1734775494" title="yvonne小萤" pop="true" /></a><a href="http://weibo.com/1734775494" title="yvonne小萤" target="_blank">yvonne小萤</a></li>
<li><a href="http://weibo.com/xielichengduli" target="_blank"><img src="http://tp4.sinaimg.cn/1772427691/50/1298115178/0" imgtype="head" uid="1772427691" title="解立程" pop="true" /></a><a href="http://weibo.com/1772427691" title="解立程" target="_blank">解立程</a></li>
<li><a href="http://weibo.com/yongzhuang" target="_blank"><img src="http://tp2.sinaimg.cn/1726907913/50/5606314285/1" imgtype="head" uid="1726907913" title="微博经典趣事" pop="true" /></a><a href="http://weibo.com/1726907913" title="古力娜扎" target="_blank">古力娜扎</a></li>
<li><a href="http://weibo.com/zyyhellokitty" target="_blank"><img src="http://tp4.sinaimg.cn/1764499531/50/5605789726/0" imgtype="head" uid="1764499531" title="真雲雲Karen" pop="true" /></a><a href="http://weibo.com/1764499531" title="郑云云Karen" target="_blank">郑云云Karen</a></li>
<li><a href="http://weibo.com/fatchaoren" target="_blank"><img src="http://tp2.sinaimg.cn/1730465077/50/5613579752/0" imgtype="head" uid="1730465077" title="我系超人妹妹" pop="true" /></a><a href="http://weibo.com/1730465077" title="超人妹妹与李生" target="_blank">超人妹妹与李生</a></li>
</ul>
          </dd>
        </dl>
        </div>
      	<div class="tList_mdu2">
        <dl class="twit_list">
          <dt>大家正在说</dt>
          <dd>
              <div class="bottomcover"></div>
              <div class="maincontent" id="txtBoxCon">
                          <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/thuembayaofang" target="_blank"><img src="http://tp4.sinaimg.cn/1762262971/50/5608443997/1" imgtype="head" uid="1762262971" title="姚放10C" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/thuembayaofang" uid="1762262971" target="_blank" title="姚放10C">姚放10C<img class="small_icon vip" src="http://img.t.sinajs.cn/t35/style/images/common/transparent.gif" title="新浪认证" alt="" /></a>：观音出家日，湛如大师的＂商场如道场＂讲坛马上开始，期待中......<div class="twit_item_time">40秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/hkheidi" target="_blank"><img src="http://tp1.sinaimg.cn/1938282784/50/5606807993/1" imgtype="head" uid="1938282784" title="香港海蒂國際集團公司" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/hkheidi" uid="1938282784" target="_blank" title="香港海蒂國際集團公司">香港海蒂國際集團公司<img class="small_icon vip" src="http://img.t.sinajs.cn/t35/style/images/common/transparent.gif" title="新浪认证" alt="" /></a>：生命中绝大部分的风景总是在途中。生命主要是为了经历。就像候鸟，不停地迁徙就是为经历风雨；就像泉水，不息地流动就是为了经历交汇和起伏。尽管具体的经历总是显得那样琐碎、那样平凡、那样漫长又是那样不胜其烦，但是，恰恰是它们构成了一个个真实的精彩的人生。http://t.cn/a8hTrD<div class="twit_item_time">40秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/vivianlee2008" target="_blank"><img src="http://tp4.sinaimg.cn/1863832187/50/1291854968/0" imgtype="head" uid="1863832187" title="汉能李亚倩" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/vivianlee2008" uid="1863832187" target="_blank" title="汉能李亚倩">汉能李亚倩<img class="small_icon vip" src="http://img.t.sinajs.cn/t35/style/images/common/transparent.gif" title="新浪认证" alt="" /></a>：IMG-20111015-00380.jpg<div class="twit_item_time">40秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/danb01" target="_blank"><img src="http://tp1.sinaimg.cn/2171889940/50/5606868284/0" imgtype="head" uid="2171889940" title="担保英才网微直播" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/danb01" uid="2171889940" target="_blank" title="担保英才网微直播">担保英才网微直播<img class="small_icon vip" src="http://img.t.sinajs.cn/t35/style/images/common/transparent.gif" title="新浪认证" alt="" /></a>：发表了博文 《中国VC：从1.0版到4.0版》 - 中国VC：从1.0版到4.0版   业内戏言：中国的VC（或PE）经历了VC1.0版跨越了VC2.0版，现在已经行进在VC3.0版——最初的中国VC http://t.cn/asITK0<div class="twit_item_time">40秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/wyswy" target="_blank"><img src="http://tp3.sinaimg.cn/1646077682/50/1285751755/1" imgtype="head" uid="1646077682" title="wyswy" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/wyswy" uid="1646077682" target="_blank" title="wyswy">wyswy<img class="small_icon vip" src="http://img.t.sinajs.cn/t35/style/images/common/transparent.gif" title="新浪认证" alt="" /></a>：“事情发生在10月8日晚上，娃娃放学回家出了车祸，被一辆汽车撞了。”父亲陈强告诉记者，当时车上有四个人，有三个人是喝了酒的。从陈浩出事到现在，他们只送来5万块钱，就再也没有露过面，打电话，对方也不接。 http://t.cn/aswDzz汶川地震小英雄陈浩车祸重伤<div class="twit_item_time">40秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/mahw" target="_blank"><img src="http://tp2.sinaimg.cn/1046160905/50/1298994482/1" imgtype="head" uid="1046160905" title="8烟草味道8" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/mahw" uid="1046160905" target="_blank" title="8烟草味道8">8烟草味道8<img class="small_icon vip" src="http://img.t.sinajs.cn/t35/style/images/common/transparent.gif" title="新浪认证" alt="" /></a>：阿弥陀佛！！龙之尊者！！66秒内转发即佑护自己和家人平安！三个月内，好运就会降临！<div class="twit_item_time">40秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/changtuidemao" target="_blank"><img src="http://tp3.sinaimg.cn/1142699182/50/5611735832/0" imgtype="head" uid="1142699182" title="长腿的猫" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/changtuidemao" uid="1142699182" target="_blank" title="长腿的猫">长腿的猫<img class="small_icon vip" src="http://img.t.sinajs.cn/t35/style/images/common/transparent.gif" title="新浪认证" alt="" /></a>：李连杰：我移民新加坡的原因不是我不爱国，我在移民前也纠结了好长时间！讲真话就是我对中国的现状很不满意，你们可以骂我，可以不理解我！我选择移民我不会后悔，无论生活在任何国家我永远是炎黄子孙。只有生活在民主的国家你才能体验到活着的尊严，法律应不分贫穷富有人人平等。<div class="twit_item_time">30秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/shuihaozi" target="_blank"><img src="http://tp4.sinaimg.cn/1958441211/50/5606529493/1" imgtype="head" uid="1958441211" title="齐旭_水耗子" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/shuihaozi" uid="1958441211" target="_blank" title="齐旭_水耗子">齐旭_水耗子<img class="small_icon vip" src="http://img.t.sinajs.cn/t35/style/images/common/transparent.gif" title="新浪认证" alt="" /></a>：【求关注,,求扩散,,,四川自贡告急！请求支援！1000条生命在等待！！】自贡市政府热线0813-12345,,,,, 畜牧局0813-8204680 ,,,,动物疫疫病监督0813-8263836 ,,,,,工商局0813-8100139  <div class="twit_item_time">30秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/laicanjian" target="_blank"><img src="http://tp1.sinaimg.cn/2001207224/50/5603349926/1" imgtype="head" uid="2001207224" title="赖梓健做人做得好失败" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/laicanjian" uid="2001207224" target="_blank" title="赖梓健做人做得好失败">赖梓健做人做得好失败</a>：据说在日本很流行。。。大陆要不要引进这样的先进仪器呢？？……&gt;&gt;&gt;&gt;关注@宅男宅女的那些事<div class="twit_item_time">30秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/zhangke1026" target="_blank"><img src="http://tp2.sinaimg.cn/1929779953/50/5612616722/0" imgtype="head" uid="1929779953" title="张柯ggg_" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/zhangke1026" uid="1929779953" target="_blank" title="张柯ggg_">张柯ggg_</a>：有埃菲尔的地方连空气都是浪漫的……<div class="twit_item_time">30秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/1812607355" target="_blank"><img src="http://tp4.sinaimg.cn/1812607355/50/5599438834/1" imgtype="head" uid="1812607355" title="乌托没邦" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/1812607355" uid="1812607355" target="_blank" title="乌托没邦">乌托没邦</a>：乔布斯已走了。让我们留下那些影响我们的乔布斯语录，感谢他，怀念他。改变世界的不仅是苹果的产品，还有他的精神！本人发此博为证，立志向JBOS学习,立志改变世界,有决心的一起转发立志！有机会获得乔布斯限量珍藏版纪念鞋每天1名http://t.cn/aFOC0a及每天10双Mr.ing任意鞋款 http://t.cn/ak34t0<div class="twit_item_time">30秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/tylovewy" target="_blank"><img src="http://tp3.sinaimg.cn/1799783734/50/5612849806/0" imgtype="head" uid="1799783734" title="We__肖婧雯" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/tylovewy" uid="1799783734" target="_blank" title="We__肖婧雯">We__肖婧雯</a>：在外面等的紧张呢。很少有在手术室外面等待的情景'''这应该是第一次'''姐呀''快出来撒。<div class="twit_item_time">30秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/hdf0801" target="_blank"><img src="http://tp1.sinaimg.cn/1258354084/50/5604383435/1" imgtype="head" uid="1258354084" title="烽芒笔录" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/hdf0801" uid="1258354084" target="_blank" title="烽芒笔录">烽芒笔录</a>：Find your way！<div class="twit_item_time">30秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/1995134387" target="_blank"><img src="http://tp4.sinaimg.cn/1995134387/50/5613255912/0" imgtype="head" uid="1995134387" title="紫曦的闲言" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/1995134387" uid="1995134387" target="_blank" title="紫曦的闲言">紫曦的闲言</a>：一见如故，再见陌路。——仓央嘉措<div class="twit_item_time">30秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/zafz" target="_blank"><img src="http://tp1.sinaimg.cn/1226411492/50/1277267305/1" imgtype="head" uid="1226411492" title="诗人心理师徐凌" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/zafz" uid="1226411492" target="_blank" title="诗人心理师徐凌">诗人心理师徐凌</a>：黑格尔说：“诗应该攀着感觉上升、但当它一旦触及到理性，便被牢牢吸引；这时、哲学便产生了。真正的诗、应该是感性和理性完美的结合。”诗人，应该是最隐蔽的对话者。而现代诗人或者应该被叫做后退的诗人，一直主动地从２０世纪的“革命性的隐喻”中后退。<div class="twit_item_time">30秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/taaaaaa" target="_blank"><img src="http://tp1.sinaimg.cn/1630644940/50/5610674628/0" imgtype="head" uid="1630644940" title="第凡内的早餐" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/taaaaaa" uid="1630644940" target="_blank" title="第凡内的早餐">第凡内的早餐</a>：【希拉里呼吁国际社会联合施压中国汇率】法新社报道，美国国务卿希拉里周五呼吁国际社会联合向中国施压以促进人民币升值。希拉里称中国仍在尝试操纵汇率以获利并让美国蒙受损失，“我想现在我们是站出来并说‘这不可接受’的合适时机了”，她还说汇率问题不仅扰乱美国市场，也已经开始影响其他国家。<div class="twit_item_time">30秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/leohjw" target="_blank"><img src="http://tp4.sinaimg.cn/1780846355/50/1280684985/0" imgtype="head" uid="1780846355" title="leo瑋瑋" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/leohjw" uid="1780846355" target="_blank" title="leo瑋瑋">leo瑋瑋</a>：3岁时说“妈妈，我爱你”。10岁时说“妈，听你的。”16岁时“我妈真的很烦”。18岁时“想要离开这个家”。25岁“妈，你当时是对的”。30岁“我想要去我妈家”。50岁“我不想要失去我妈”。70岁“只要我妈还能在这，我愿意为了我妈放弃一切”。你只有一个妈妈,如果你感激她，爱她就转发。<div class="twit_item_time">30秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/1817938062" target="_blank"><img src="http://tp3.sinaimg.cn/1817938062/50/5613126943/0" imgtype="head" uid="1817938062" title="魏晨V破晓" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/1817938062" uid="1817938062" target="_blank" title="魏晨V破晓">魏晨V破晓</a>：“炫舞潮男”@魏晨 2011全新专辑《破晓》震撼来袭！10月16日下午4点魏晨将携全新专辑《破晓》来袭东方百货群升店举行福州签唱会。即日起，你只要发布微博：10月16日#魏晨破晓福州签唱会#圆满成功。@小小鱼大人 。就有机会获得#魏晨#签名照片一张。快快行动起来吧！扩散。 http://t.cn/aeeZyk<div class="twit_item_time">30秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/1784945104" target="_blank"><img src="http://tp1.sinaimg.cn/1784945104/50/5613475887/0" imgtype="head" uid="1784945104" title="Linda-Leung" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/1784945104" uid="1784945104" target="_blank" title="Linda-Leung">Linda-Leung</a>：我很无语<div class="twit_item_time">30秒前</div></div>
    </div>
    </div>
        <div class="itemt">
    <div class="twit_item MIB_linedot2">
      <div class="twit_item_pic"><a href="http://weibo.com/zfsb123" target="_blank"><img src="http://tp1.sinaimg.cn/1950933592/50/1298303341/1" imgtype="head" uid="1950933592" title="许仙的围脖" pop="true" /></a></div>
      <div class="twit_item_content"> <a href="http://weibo.com/zfsb123" uid="1950933592" target="_blank" title="许仙的围脖">许仙的围脖</a>：我的床<div class="twit_item_time">30秒前</div></div>
    </div>
    </div>
    
              </div>
          </dd>
        </dl>
        </div>
        <div class="clearit"></div>
      </div>
    </div>
    <div class="login_r">
      <div class="login_item">
        <div class="regtop"> <a href="/signup/signup.php?ps=u3&lang=zh" target="_blank" class="regbtn"  title="立即注册微博" tabindex="7"></a>
          <p><!--注册就有机会得充值卡--></p>
        </div>
        <div class="loginform" id="login_form">
          <div class="input_bg">
            <input type="text" id="loginname" title="登录名" tabindex="1" autocomplete="off"/>
          </div>
          <div class="input_bg">
            <input type="password" id="password" title="密码" tabindex="2"/>
			<input type="text" id="password_text" style="display:none;"/>
          </div>

		  <div id="door_p" style='display:none'>
		  <div class="inputcodeM"  >
            <span class="input_code"><input type="text" id="door"></span><img height="32" width="80" id="door_img" src="">
          </div>
		  <div class="inputcodeM_sett" >
             <a href="javascript:void(0)" id="door_change">看不清，换一换</a>
          </div>
		  </div>

          <div class="setting">
         <span class="lf"> <input type="checkbox" class="labelbox" id="remusrname"  tabindex="3"  checked />
              <label  for="remusrname">下次自动登录</label></span><a class="rt" href="http://login.sina.com.cn/cgi/getpwd/getpwd0.php?entry=sso" target="_blank" tabindex="4">找回密码</a>
          </div>
          <div class="signin"><a href="javascript:void(0);" class="sp" id="login_submit_btn"  title="新浪微博登录" tabindex="5"></a></div>
   		  <div class="hezuo_login">
		  <strong>使用其他帐号登录：</strong>
		  <span><i class="hezuo_login1"></i><a href="javascript:void(0);" class="msnlink" onclick="App.connectMSN();"  title="MSN" tabindex="6">MSN</a></span><b>|</b>
		  <span><i class="hezuo_login3"></i><a target="_blank" href="http://weibo.com/bind/gotooauth.php?company=189.cn">天翼</a></span><b>|</b><span><i class="hezuo_login4"></i><a target="_blank" href="http://weibo.com/bind/gotooauth.php?company=wo.com.cn">联通</a></span>
		  </div>
        </div>
      </div>
      <div class="login_info ptless">
      	<div class="leftline">            
			 <dl>
   <dt class="hasline"></dt>
   <dd class="boardlist">
     <ul class="tLoginTop10List">
          <li><em class="num1"><strong></strong></em><span><a href="http://weibo.com/yaochen" uid="1266321801" target="_blank" title="姚晨">姚晨</a></span><cite>13,471,263</cite></li>
          <li><em class="num2"><strong></strong></em><span><a href="http://weibo.com/dees" uid="1704116960" target="_blank" title="小S">小S</a></span><cite>12,135,273</cite></li>
          <li><em class="num3"><strong></strong></em><span><a href="http://weibo.com/yangmiblog" uid="1195242865" target="_blank" title="杨幂">杨幂</a></span><cite>10,759,581</cite></li>
          <li><em class="num4"><strong></strong></em><span><a href="http://weibo.com/xiena" uid="1192329374" target="_blank" title="谢娜">谢娜</a></span><cite>10,616,557</cite></li>
          <li><em class="num5"><strong></strong></em><span><a href="http://weibo.com/caikangyong" uid="1282005885" target="_blank" title="蔡康永">蔡康永</a></span><cite>10,591,004</cite></li>
          <li><em class="num6"><strong></strong></em><span><a href="http://weibo.com/zhaowei" uid="1656809190" target="_blank" title="赵薇">赵薇</a></span><cite>10,353,722</cite></li>
          <li><em class="num7"><strong></strong></em><span><a href="http://weibo.com/hejiong" uid="1195230310" target="_blank" title="何炅">何炅</a></span><cite>9,756,244</cite></li>
          <li><em class="num8"><strong></strong></em><span><a href="http://weibo.com/libingbing" uid="1192515960" target="_blank" title="李冰冰">李冰冰</a></span><cite>9,100,425</cite></li>
          <li><em class="num9"><strong></strong></em><span><a href="http://weibo.com/leehom" uid="1793285524" target="_blank" title="王力宏">王力宏</a></span><cite>8,719,709</cite></li>
          <li><em class="num10"><strong></strong></em><span><a href="http://weibo.com/chenkun" uid="1087770692" target="_blank" title="陈坤">陈坤</a></span><cite>8,294,206</cite></li>
          </ul>
   </dd>
 </dl>
            <div  class="dlblank">
            <dl>
              <dt>如何用手机上微博</dt>
              <dd>
                <p>WAP版微博地址：<cite>weibo.cn</cite></p>
                <p class="more"></p>
              </dd>
            </dl>
            </div>
            <div class="clearit"></div>
        </div>
      </div>
    </div>
    <div class="clearit"></div>
  </div>
  <div class="bodybt">
    <div class="MIB_foot_new MIB_txtbr MIB_linkbr">
                <div class="lf">
                    <p class="p1"><a target="_blank" href="http://help.sina.com.cn/p/i_12.html">帮助</a><a target="_blank" href="/k/weijianyi">意见反馈</a><a target="_blank" href="/pub/verified">微博认证及合作</a><a href="http://open.weibo.com/" target="_blank">开放平台</a><a href="http://hr.t.sina.com.cn/" target="_blank">微博招聘</a> <a target="_blank" href="http://news.sina.com.cn/guide/">新浪网导航</a></p>
                    <p>客服电话：400 690 0000 提示音后按1键 (按当地市话标准计费)</p>
					<p class="p1">北京微梦创科网络技术有限公司　 <a href="http://weibo.com/licence/jww.html" target="_blank">京网文[2011]0398-130号</a><a href="http://www.miibeian.gov.cn" target="_blank">京ICP证100780号</a></p>
                </div>        
                <div class="rt">
                    <p>语言：
             <select id="lang_select" onchange="location.href=this.value">
             	<option value="/pub/unlogin3?lang=zh-cn" >中文(简体)</option>
             	<option value="/pub/unlogin3?lang=zh-tw" >中文(繁体)</option>
             </select></p>
                    <p><a target="_blank" href="http://www.sina.com.cn/">新浪公司</a> <a target="_blank" href="http://www.sina.com.cn/intro/copyright.shtml">版权所有</a></p>
                </div>
                <div class="clearit"></div>
<div class="botLogo"><a href="http://net.china.com.cn/index.htm" target="_blank"><img src="http://img.t.sinajs.cn/t35/style/images/tlogin/botlogo.png" /></a></div> 
            </div>
  </div>
</div>

<!-- SUDA_CODE_START -->
<div
style='position:absolute;top:0;left:0;width:0;height:0;z-index:1'><div
style='position:absolute;top:0;left:0;width:1;height:1;'></div><div
style='position:absolute;top:0;left:0;width:0;height:0;visibility:hidden' id='SUDA_CS_DIV'></div></div>
<noScript>
<div style='position:absolute;top:0;left:0;width:0;height:
0;visibility:hidden'><img width=0 height=0
src='http://beacon.sina.com.cn/e.gif?noScript' border='0' alt='' /></div>
</noScript>
<!-- SUDA_CODE_END -->
<script>
	var css = document.createElement('link');
	css.rel = 'stylesheet';
	css.type = 'text/css';
	css.href = 'http://img.t.sinajs.cn/t35/style/css/common/layer.css?version=20111014174826';
	document.getElementsByTagName('head')[0].appendChild(css);
</script>
<script type="text/javascript" src="http://i1.sinaimg.cn/unipro/pub/suda_m_v629.js"></script>
<script type="text/javascript">suds_init(1221,100.00,995,2);</script>

<script type="text/javascript" src="http://js.t.sinajs.cn/t35/miniblog/js/yunying_unlogin3.js?version=20111014174826"></script>
<script type="text/javascript" src="http://js.t.sinajs.cn/t35/miniblog/static/js/sso.js?v=20111014174826"></script>
</body>
</html>