name: analysisme
version: 1
accesskey: xljwmj4j4m
cron:
   - description: cron me
	 url: save_data.php?uid=1651712685
	 schedule: */30 * * * *
   - description: cron yr
	 url: save_data.php?uid=1876063045
	 schedule: */30 * * * *
